"""v.9

Revision ID: 330fce865cbe
Revises: 994d4f48285d
Create Date: 2024-01-29 09:51:18.593390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330fce865cbe'
down_revision = '994d4f48285d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carousel_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_text', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carousel_item', schema=None) as batch_op:
        batch_op.drop_column('link_text')

    # ### end Alembic commands ###
