"""v.22

Revision ID: 8bafbf57dfa6
Revises: 80abc08e8d8d
Create Date: 2024-01-31 19:46:47.203903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bafbf57dfa6'
down_revision = '80abc08e8d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carousel_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_resposta_carousel_item', 'carousel_item', ['carousel_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resposta', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resposta_carousel_item', type_='foreignkey')
        batch_op.drop_column('carousel_item_id')

    # ### end Alembic commands ###
