"""v.8

Revision ID: 994d4f48285d
Revises: 816e569471d4
Create Date: 2024-01-29 09:41:24.498731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994d4f48285d'
down_revision = '816e569471d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carousel_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('link_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carousel_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_text', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('team_type')

    # ### end Alembic commands ###
